Задание 6. Доработана и улучшена логика регистрации. #11
gpb-it-factory/danyukovas-middle-service pull request #12
Opened 2024-06-22 15:26 UTC by SiuSpacecowboy

2024-06-22 15:29 UTC, SiuSpacecowboy commented
Я пытался сконфигурировать несколько часов @ConditionalOnProperty в отдельном yml файле, но ничего не получилось, нормально ли конфигурировать его в application.yml и можно ли это сделать в другом файле?
Хотелось бы узнать по моему коду следующие вещи:
Хорошо ли сделано мое тестирование, насколько оптимально создан интеграционный тест? Стоит ли покрывать что-то еще из кода? Стоит ли добавлять что-то еще?
Насколько имеет смысл создавать приватный метод для обработки логики ExceptionHadler, как это сделал я, или стоило реализовать ее внутри обработчика (в классе GlobalExceptionhandler)?
Буду невероятно рад фидбеку 👍

2024-06-25 18:37 UTC, vaganov-vadim commented
Конечно, проперти для @ConditionalOnProperty лежат в application.yaml, почему нет.

2024-06-26 17:46 UTC, vaganov-vadim requested changes
Привет! Крутая работа. Добавил комменты по коду, в том числе по твоим вопросам. Единственное, не понял о чём был вопрос по поводу обработки ошибок. Поясни в комментах, пожалуйста.

2024-06-26 17:46 UTC, vaganov-vadim commented on middle-service-app/src/main/java/middle/example/gpb/config/RestClientConfig.java
> +    public RestClientConfig(@Value("${httpclient.maxConPerRoute}") int maxConPerRoute,
Когда становится так много связанных конфигурационных свойств, то проще их переводить в Properties (я вообще использую Properties всегда, они удобнее и типизированные). Это как совет на развитие https://www.baeldung.com/configuration-properties-in-spring-boot

2024-06-26 17:46 UTC, vaganov-vadim commented on middle-service-app/src/main/java/middle/example/gpb/controllers/AccountController.java
> +/*package middle.example.gpb.controllers;
Почему-то закомменченый код. Либо удалить, либо раскомментировать.

2024-06-26 17:46 UTC, vaganov-vadim commented on middle-service-app/src/main/java/middle/example/gpb/controllers/UsersController.java
> +    public ResponseEntity<String> registerNewUser(@Valid @RequestBody CreateUserRequestV2 newUser) {
Лучше для возвращаемых значений тоже создавать DTO. Объясню почему. В будущем вероятно нужно добавить что-то в возвращаемые значения. Добавление необязательного поля в модель - неломающее изменение, а вот замена строки на объект - ломающее. Лучше быть заранее к этому готовым.

2024-06-26 17:46 UTC, vaganov-vadim commented on middle-service-app/src/main/java/middle/example/gpb/exeptions/CustomBackendServiceRuntimeException.java
> +    @SneakyThrows
Опасная фигня, лучше не использовать.

2024-06-26 17:46 UTC, vaganov-vadim commented on middle-service-app/src/main/java/middle/example/gpb/services/AccountService.java
> +/*package middle.example.gpb.services;
Опять закомментировано.

2024-06-26 17:46 UTC, vaganov-vadim commented on middle-service-app/src/test/java/middle/example/gpb/controllers/UsersControllerITTest.java
> +        verify(userService, times(1)).responseFromBackend(new CreateUserRequestV2(12L, "test"));
Это не самая оптимальная проверка. Получается, мы полностью знаем как работает наш код внутри. Лучше проверять поведение. Вход -> выход. Проверяя что сколько раз вызывается мы делаем тесты, которые будут падать при любом рефакторинге, то есть такие тесты хрупки. Завязывайся на контракт - какие входные значения будут при определённых входных.

2024-06-26 17:46 UTC, vaganov-vadim commented on middle-service-app/src/test/java/middle/example/gpb/controllers/UsersControllerITTest.java
> +    public void whenValidDataTest() throws Exception {
Названием теста лучше делать проверяемый факт. Например "Запрос в невалидной датой завершается ошибкой" или что-то вроде того. Также полезно использовать аннотацию DisplayName.

2024-06-27 14:45 UTC, SiuSpacecowboy commented on middle-service-app/src/main/java/middle/example/gpb/controllers/UsersController.java
> +    public ResponseEntity<String> registerNewUser(@Valid @RequestBody CreateUserRequestV2 newUser) {
@vaganov-vadim отправил вопрос в тг

2024-06-28 19:14 UTC, SiuSpacecowboy commented on middle-service-app/src/main/java/middle/example/gpb/services/AccountService.java
> +/*package middle.example.gpb.services;
удалил

2024-06-28 19:28 UTC, SiuSpacecowboy commented on middle-service-app/src/main/java/middle/example/gpb/config/RestClientConfig.java
> +    public RestClientConfig(@Value("${httpclient.maxConPerRoute}") int maxConPerRoute,
Готово, я сначала пытался так сконфигурировать, но у меня не получилось. Сейчас я заметил, что нужны геттеры и сеттеры. :+1:

2024-06-28 20:08 UTC, SiuSpacecowboy commented on middle-service-app/src/test/java/middle/example/gpb/controllers/UsersControllerITTest.java
> +    public void whenValidDataTest() throws Exception {
готово

2024-06-28 22:18 UTC, SiuSpacecowboy commented on middle-service-app/src/main/java/middle/example/gpb/controllers/UsersController.java
> +    public ResponseEntity<String> registerNewUser(@Valid @RequestBody CreateUserRequestV2 newUser) {
Готово

2024-06-28 22:20 UTC, SiuSpacecowboy commented on middle-service-app/src/main/java/middle/example/gpb/exeptions/CustomBackendServiceRuntimeException.java
> +    @SneakyThrows
Готово

2024-06-28 22:21 UTC, SiuSpacecowboy commented on middle-service-app/src/main/java/middle/example/gpb/controllers/AccountController.java
> +/*package middle.example.gpb.controllers;
готово

2024-06-28 22:27 UTC, SiuSpacecowboy commented on middle-service-app/src/test/java/middle/example/gpb/controllers/UsersControllerITTest.java
> +        verify(userService, times(1)).responseFromBackend(new CreateUserRequestV2(12L, "test"));
Идею понял, классно, до этого по факту были сделаны проверки ради проверок. Добавил еще один тест на проверку противоположного исхода вход -> выход. Спасибо за наставление :+1:

2024-06-29 10:14 UTC, vaganov-vadim approved these changes
Круто поработал. Аппрув.

2024-06-29 14:41 UTC, merged